In [4]:

# No terminal, uma vez: python -m pip install openpyxl pandas
import pandas as pd
import openpyxl

In [ ]:
path = r"Tabela_11_Domicilios_sem_presenca_de_conjuge_e_com_filhos.xlsx"

# Sexo da pessoa responsável pelo domicílio

In [7]:
#Lé todas as abas do arquivo
todas = pd.read_excel(path, sheet_name=None, header=None)
print(todas.keys())

dict_keys(['BR GR UF MU', 'Tabela base do SIDRA 9882'])

In [8]:
bruto = pd.read_excel(path, sheet_name="Tabela base do SIDRA 9882", header=None)

In [9]:
bruto

,0,1,2,3
0,"Tabela 9882 - Domicílios particulares, por pre...",NaN,NaN,NaN
1,Variável - Domicílios particulares (Domicílios),NaN,NaN,NaN
2,Ano - 2022,NaN,NaN,NaN
3,"Brasil, Grande Região, Unidade da Federação e ...",Sexo da pessoa responsável pelo domicílio,NaN,NaN
4,NaN,Total,Homens,Mulheres
...,...,...,...,...
5604,Vicentinópolis (GO),352,55,297
5605,Vila Boa (GO),226,37,189
5606,Vila Propício (GO),267,49,218
5607,Brasília (DF),184921,24110,160811
5608,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN

In [10]:
indicador_2 = bruto.iloc[5:5608].copy()

In [11]:
indicador_2

                        0         1        2         3
5                  Brasil  11936510  1614739  10321771
6                   Norte    909212   149246    759966
7                Nordeste   3487048   411968   3075080
8                 Sudeste   5105674   700511   4405163
9                     Sul   1537469   228801   1308668
...                   ...       ...      ...       ...
5603      Vianópolis (GO)       689       87       602
5604  Vicentinópolis (GO)       352       55       297
5605        Vila Boa (GO)       226       37       189
5606   Vila Propício (GO)       267       49       218
5607        Brasília (DF)    184921    24110    160811

[5603 rows x 4 columns]

In [12]:
# Preenchendo os nomes das colunas
indicador_2.columns = [
    "regiao",
    "total",
    "homens",
    "mulheres",
]

In [10]:
indicador_2 = indicador_2.reset_index(drop=True)

# horas são número, não texto
for col in indicador_2.columns[1:]:
    indicador_2[col] = pd.to_numeric(indicador_2[col], errors="coerce")

indicador_2

                   regiao     total   homens  mulheres
0                  Brasil  11936510  1614739  10321771
1                   Norte    909212   149246    759966
2                Nordeste   3487048   411968   3075080
3                 Sudeste   5105674   700511   4405163
4                     Sul   1537469   228801   1308668
...                   ...       ...      ...       ...
5598      Vianópolis (GO)       689       87       602
5599  Vicentinópolis (GO)       352       55       297
5600        Vila Boa (GO)       226       37       189
5601   Vila Propício (GO)       267       49       218
5602        Brasília (DF)    184921    24110    160811

[5603 rows x 4 columns]

In [11]:
indicador_2.describe()

              total        homens      mulheres
count  5.603000e+03  5.603000e+03  5.603000e+03
mean   8.521513e+03  1.152767e+03  7.368746e+03
std    1.879794e+05  2.535391e+04  1.626494e+05
min    2.300000e+01  3.000000e+00  1.600000e+01
25%    2.500000e+02  4.000000e+01  2.090000e+02
50%    5.660000e+02  8.700000e+01  4.730000e+02
75%    1.323500e+03  1.890000e+02  1.134000e+03
max    1.193651e+07  1.614739e+06  1.032177e+07

In [12]:
indicador_2.describe().round(2)

             total      homens     mulheres
count      5603.00     5603.00      5603.00
mean       8521.51     1152.77      7368.75
std      187979.37    25353.91    162649.37
min          23.00        3.00        16.00
25%         250.00       40.00       209.00
50%         566.00       87.00       473.00
75%        1323.50      189.00      1134.00
max    11936510.00  1614739.00  10321771.00

EXCLUIR AS CIDADES, REPAREM NO PADRÃO, ELAS TEM O () QUE INDICAM O UF

In [13]:
indicador_2 = indicador_2[~indicador_2["regiao"].str.contains(r"\(", na=False)]
indicador_2

                 regiao     total   homens  mulheres
0                Brasil  11936510  1614739  10321771
1                 Norte    909212   149246    759966
2              Nordeste   3487048   411968   3075080
3               Sudeste   5105674   700511   4405163
4                   Sul   1537469   228801   1308668
5          Centro-Oeste    897107   124213    772894
6              Rondônia     78597    12520     66077
7                  Acre     47506     7166     40340
8              Amazonas    205036    37693    167343
9               Roraima     31690     5072     26618
10                 Pará    423309    67853    355456
11                Amapá     42958     7288     35670
12            Tocantins     80116    11654     68462
13             Maranhão    384488    50219    334269
14                Piauí    192425    23505    168920
15                Ceará    558869    64440    494429
16  Rio Grande do Norte    204565    24132    180433
17              Paraíba    240849    27585    213264
18           Pernambuco    598783    64573    534210
19              Alagoas    192706    21961    170745
20              Sergipe    155980    16312    139668
21                Bahia    958383   119241    839142
22         Minas Gerais   1258188   171679   1086509
23       Espírito Santo    214564    30152    184412
24       Rio de Janeiro   1067294   146596    920698
25            São Paulo   2565628   352084   2213544
26               Paraná    593410    85773    507637
27       Santa Catarina    340157    53269    286888
28    Rio Grande do Sul    603902    89759    514143
29   Mato Grosso do Sul    150374    21034    129340
30          Mato Grosso    172804    26431    146373
31                Goiás    389008    52638    336370
32     Distrito Federal    184921    24110    160811

# Trazer a Tabela 1.1.1 (horas de trabalho doméstico) e juntar com indicador_2

In [ ]:
# Mesma limpeza da Aula 2: linhas 8–40, nomes de coluna, horas como número
path_horas = r"Tabela 1.1.1.xls"
bruto_1 = pd.read_excel(path_horas, engine="xlrd", header=None)

indicador_1 = bruto_1.iloc[8:41].copy()
indicador_1.columns = [
    "uf_regiao",
    "total",
    "total_branca",
    "total_preta_parda",
    "homem_branca",
    "homem_preta_parda",
    "mulher_branca",
    "mulher_preta_parda",
]
indicador_1 = indicador_1.reset_index(drop=True)
for col in indicador_1.columns[1:]:
    indicador_1[col] = pd.to_numeric(indicador_1[col], errors="coerce")

indicador_1

,uf_regiao,total,total_branca,total_preta_parda,homem_branca,homem_preta_parda,mulher_branca,mulher_preta_parda
0,Brasil,16.985781,16.545930,17.333142,11.705136,11.746330,20.404106,22.037998
1,Norte,16.187037,15.925246,16.256032,11.588653,11.514646,19.295780,20.534188
2,Rondônia,17.014162,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410
3,Acre,13.606903,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754
4,Amazonas,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
5,Roraima,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
6,Pará,16.474268,16.181627,16.560239,11.524306,11.026707,19.835110,21.591144
7,Amapá,13.586656,14.389180,13.415091,11.116821,10.749444,16.648579,15.908487
8,Tocantins,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
9,Nordeste,18.499396,18.151700,18.610911,11.723907,11.848436,22.744666,23.716716
10,Maranhão,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
11,Piauí,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.695440
12,Ceará,19.499293,18.527120,19.882469,12.186936,12.821323,23.019718,24.952274
13,Rio Grande do Norte,18.307740,18.101853,18.445218,11.166909,11.086286,23.547080,24.422884
14,Paraíba,18.920816,18.887920,18.945306,12.480204,12.400831,23.642936,24.035650
15,Pernambuco,19.306249,18.950219,19.418444,12.312833,12.868821,23.357880,24.243396
16,Alagoas,20.217129,19.165111,20.560451,12.121839,13.357160,24.093655,25.856637
17,Sergipe,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
18,Bahia,17.849776,17.538007,17.935566,10.551673,10.982808,22.572730,23.217119
19,Sudeste,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
20,Minas Gerais,17.502141,17.179387,17.707564,11.319720,11.619120,22.186650,23.075751
21,Espírito Santo,17.111106,16.510610,17.478861,11.798571,12.017589,20.464462,22.196626
22,Rio de Janeiro,16.716263,16.097467,17.243060,12.000036,12.864896,19.203741,20.957728
23,São Paulo,17.071295,16.964437,17.255480,12.123044,12.235200,20.771186,21.767620
24,Sul,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
25,Paraná,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.365380
26,Santa Catarina,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
27,Rio Grande do Sul,15.356709,15.337269,15.448203,11.308447,11.519941,18.868230,19.107720
28,Centro-Oeste,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.331040
29,Mato Grosso do Sul,15.309783,14.902105,15.567204,10.446213,11.126920,18.593200,19.542761
30,Mato Grosso,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
31,Goiás,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
32,Distrito Federal,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332

In [26]:
# Left join: fica tudo de indicador_2; puxa as horas da 1.1.1 quando o nome bate
# suffixes: as duas tabelas têm coluna "total" — domicílios vs horas
indicador1e2 = indicador_2.merge(
    indicador_1,
    how="left",
    left_on="regiao",
    right_on="uf_regiao",
    suffixes=("_domicilios", "_horas"),
)
indicador1e2 = indicador1e2.drop(columns=["uf_regiao"])

In [27]:
indicador1e2 = indicador1e2.rename(columns={
    "homens": "resp_domicilio_homens",
    "mulheres": "resp_domicilio_mulheres",
})
indicador1e2

,regiao,total_domicilios,resp_domicilio_homens,resp_domicilio_mulheres,mais_mulheres,total_horas,total_branca,total_preta_parda,homem_branca,homem_preta_parda,mulher_branca,mulher_preta_parda
0,Brasil,11936510,1614739,10321771,True,16.985781,16.545930,17.333142,11.705136,11.746330,20.404106,22.037998
1,Norte,909212,149246,759966,True,16.187037,15.925246,16.256032,11.588653,11.514646,19.295780,20.534188
2,Nordeste,3487048,411968,3075080,True,18.499396,18.151700,18.610911,11.723907,11.848436,22.744666,23.716716
3,Sudeste,5105674,700511,4405163,True,17.104218,16.834863,17.397989,11.933522,12.180843,20.732969,21.990431
4,Sul,1537469,228801,1308668,True,15.527769,15.570983,15.406088,11.546629,11.159487,19.012969,19.338734
5,Centro-Oeste,897107,124213,772894,True,15.000763,14.826985,15.078025,10.546799,10.332059,18.220683,19.331040
6,Rondônia,78597,12520,66077,True,17.014162,16.727733,17.101523,12.111127,12.544080,20.412887,21.061410
7,Acre,47506,7166,40340,True,13.606903,13.806929,13.541399,10.796120,9.686983,16.130352,16.710754
8,Amazonas,205036,37693,167343,True,16.807290,15.987545,16.995493,12.233043,12.822584,18.764969,20.716986
9,Roraima,31690,5072,26618,True,13.639257,13.651755,13.633606,10.814803,10.476601,16.135877,16.560244
10,Pará,423309,67853,355456,True,16.474268,16.181627,16.560239,11.524306,11.026707,19.835110,21.591144
11,Amapá,42958,7288,35670,True,13.586656,14.389180,13.415091,11.116821,10.749444,16.648579,15.908487
12,Tocantins,80116,11654,68462,True,15.815781,15.701788,15.768728,10.733863,11.682616,19.663713,19.629399
13,Maranhão,384488,50219,334269,True,16.669614,16.421773,16.708894,11.665173,11.437359,19.881056,20.739589
14,Piauí,192425,23505,168920,True,17.960366,16.948094,18.231789,12.258324,11.204814,20.494063,23.695440
15,Ceará,558869,64440,494429,True,19.499293,18.527120,19.882469,12.186936,12.821323,23.019718,24.952274
16,Rio Grande do Norte,204565,24132,180433,True,18.307740,18.101853,18.445218,11.166909,11.086286,23.547080,24.422884
17,Paraíba,240849,27585,213264,True,18.920816,18.887920,18.945306,12.480204,12.400831,23.642936,24.035650
18,Pernambuco,598783,64573,534210,True,19.306249,18.950219,19.418444,12.312833,12.868821,23.357880,24.243396
19,Alagoas,192706,21961,170745,True,20.217129,19.165111,20.560451,12.121839,13.357160,24.093655,25.856637
20,Sergipe,155980,16312,139668,True,18.826541,17.264294,19.317934,10.830511,11.270341,21.740902,25.637681
21,Bahia,958383,119241,839142,True,17.849776,17.538007,17.935566,10.551673,10.982808,22.572730,23.217119
22,Minas Gerais,1258188,171679,1086509,True,17.502141,17.179387,17.707564,11.319720,11.619120,22.186650,23.075751
23,Espírito Santo,214564,30152,184412,True,17.111106,16.510610,17.478861,11.798571,12.017589,20.464462,22.196626
24,Rio de Janeiro,1067294,146596,920698,True,16.716263,16.097467,17.243060,12.000036,12.864896,19.203741,20.957728
25,São Paulo,2565628,352084,2213544,True,17.071295,16.964437,17.255480,12.123044,12.235200,20.771186,21.767620
26,Paraná,593410,85773,507637,True,15.390122,15.453295,15.307289,11.240085,10.815611,18.896661,19.365380
27,Santa Catarina,340157,53269,286888,True,16.039355,16.124417,15.616235,12.339052,11.517342,19.414764,19.646573
28,Rio Grande do Sul,603902,89759,514143,True,15.356709,15.337269,15.448203,11.308447,11.519941,18.868230,19.107720
29,Mato Grosso do Sul,150374,21034,129340,True,15.309783,14.902105,15.567204,10.446213,11.126920,18.593200,19.542761
30,Mato Grosso,172804,26431,146373,True,14.239989,14.083513,14.270209,9.479654,9.265734,17.782825,18.695923
31,Goiás,389008,52638,336370,True,15.186471,14.962622,15.296966,10.636424,10.531883,18.440842,19.587913
32,Distrito Federal,184921,24110,160811,True,15.096351,15.061306,15.126295,11.377952,10.481279,17.738123,19.307332

In [28]:
# % de domicílios com responsável mulher  |  horas médias das mulheres (média das duas raças)
indicador1e2["pct_resp_mulheres"] = (
    indicador1e2["resp_domicilio_mulheres"] / indicador1e2["total_domicilios"] * 100
)
indicador1e2["horas_mulher"] = (
    indicador1e2["mulher_branca"] + indicador1e2["mulher_preta_parda"]
) / 2

indicador1e2[
    ["regiao", "pct_resp_mulheres", "horas_mulher", "resp_domicilio_mulheres", "total_domicilios"]
].sort_values("pct_resp_mulheres", ascending=False)

,regiao,pct_resp_mulheres,horas_mulher,resp_domicilio_mulheres,total_domicilios
20,Sergipe,89.542249,23.689292,139668,155980
18,Pernambuco,89.215960,23.800638,534210,598783
19,Alagoas,88.603884,24.975146,170745,192706
17,Paraíba,88.546766,23.839293,213264,240849
15,Ceará,88.469570,23.985996,494429,558869
16,Rio Grande do Norte,88.203261,23.984982,180433,204565
2,Nordeste,88.185766,23.230691,3075080,3487048
14,Piauí,87.784851,22.094752,168920,192425
21,Bahia,87.558106,22.894924,839142,958383
32,Distrito Federal,86.962000,18.522728,160811,184921
13,Maranhão,86.938734,20.310323,334269,384488
0,Brasil,86.472269,21.221052,10321771,11936510
31,Goiás,86.468659,19.014378,336370,389008
22,Minas Gerais,86.355060,22.631200,1086509,1258188
3,Sudeste,86.279755,21.361700,4405163,5105674
25,São Paulo,86.276888,21.269403,2213544,2565628
24,Rio de Janeiro,86.264703,20.080735,920698,1067294
5,Centro-Oeste,86.154049,18.775862,772894,897107
29,Mato Grosso do Sul,86.012210,19.067981,129340,150374
23,Espírito Santo,85.947316,21.330544,184412,214564
26,Paraná,85.545744,19.131020,507637,593410
12,Tocantins,85.453592,19.646556,68462,80116
28,Rio Grande do Sul,85.136827,18.987975,514143,603902
4,Sul,85.118334,19.175851,1308668,1537469
7,Acre,84.915590,16.420553,40340,47506
30,Mato Grosso,84.704636,18.239374,146373,172804
27,Santa Catarina,84.339878,19.530669,286888,340157
6,Rondônia,84.070639,20.737149,66077,78597
9,Roraima,83.994951,16.348061,26618,31690
10,Pará,83.970811,20.713127,355456,423309
1,Norte,83.585126,19.914984,759966,909212
11,Amapá,83.034592,16.278533,35670,42958
8,Amazonas,81.616399,19.740977,167343,205036

pct_resp_mulheres = em cada 100 desses domicílios, quantos têm mulher responsável.
horas_mulher = média semanal de horas das mulheres (média simples de branca e preta/parda na 1.1.1).
Como ler os dois juntos. Nordeste concentra os dois: Sergipe ~90% de responsáveis mulheres e ~24 h; Alagoas ~89% e ~25 h (mais horas). Norte tem menos lares com responsável mulher (Amazonas ~82%) e menos horas (Amapá, Acre, Roraima ~16 h). DF é o contraste: muitas responsáveis mulheres (~87%) e menos horas (~18,5 h).

In [29]:
# Neste recorte (sem cônjuge + com filhos): mulheres são maioria?
indicador_2["mais_mulheres"] = indicador_2["mulheres"] > indicador_2["homens"]

brasil = indicador_2.loc[indicador_2["regiao"] == "Brasil"].iloc[0]
print("Brasil — domicílios sem cônjuge e com filhos (Censo 2022)")
print(f"  mulheres: {int(brasil.mulheres):,}  ({brasil.mulheres/brasil.total*100:.1f}%)")
print(f"  homens:   {int(brasil.homens):,}  ({brasil.homens/brasil.total*100:.1f}%)")
print(f"  {brasil.mulheres/brasil.homens:.1f} mulheres para cada homem responsável")
print()
print("Em todas as UFs/regiões mulheres > homens?", indicador_2["mais_mulheres"].all())

indicador_2[["regiao", "homens", "mulheres", "mais_mulheres"]]

Brasil — domicílios sem cônjuge e com filhos (Censo 2022)
  mulheres: 10,321,771  (86.5%)
  homens:   1,614,739  (13.5%)
  6.4 mulheres para cada homem responsável

Em todas as UFs/regiões mulheres > homens? True

                 regiao   homens  mulheres  mais_mulheres
0                Brasil  1614739  10321771           True
1                 Norte   149246    759966           True
2              Nordeste   411968   3075080           True
3               Sudeste   700511   4405163           True
4                   Sul   228801   1308668           True
5          Centro-Oeste   124213    772894           True
6              Rondônia    12520     66077           True
7                  Acre     7166     40340           True
8              Amazonas    37693    167343           True
9               Roraima     5072     26618           True
10                 Pará    67853    355456           True
11                Amapá     7288     35670           True
12            Tocantins    11654     68462           True
13             Maranhão    50219    334269           True
14                Piauí    23505    168920           True
15                Ceará    64440    494429           True
16  Rio Grande do Norte    24132    180433           True
17              Paraíba    27585    213264           True
18           Pernambuco    64573    534210           True
19              Alagoas    21961    170745           True
20              Sergipe    16312    139668           True
21                Bahia   119241    839142           True
22         Minas Gerais   171679   1086509           True
23       Espírito Santo    30152    184412           True
24       Rio de Janeiro   146596    920698           True
25            São Paulo   352084   2213544           True
26               Paraná    85773    507637           True
27       Santa Catarina    53269    286888           True
28    Rio Grande do Sul    89759    514143           True
29   Mato Grosso do Sul    21034    129340           True
30          Mato Grosso    26431    146373           True
31                Goiás    52638    336370           True
32     Distrito Federal    24110    160811           True

In [5]:
path1 = r"Tabela_3_Areas_gerais_de_formacao_na_graduacao.xlsx"

In [7]:
tabela = pd.read_excel(path1, sheet_name="Sheet1", header=None)
print(tabela.keys())

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [8]:
tabela

,0,1,2,3,4,5,6,7,8,9
0,Tabela 10063 - Pessoas com nível superior comp...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Brasil, Grande Região e Unidade da Federação",Total,NaN,NaN,"Ciência, Tecnologia, Engenharias e Matemática",NaN,NaN,"Educação, Serviços pessoais, Saúde e Bem-estar",NaN,NaN
2,NaN,Total,Homens,Mulheres,Total,Homens,Mulheres,Total,Homens,Mulheres
3,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
4,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
5,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
6,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
7,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
8,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
9,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
10,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
11,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
12,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
13,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
14,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
15,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
16,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
17,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
18,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
19,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
20,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
21,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
22,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
23,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
24,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
25,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
26,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
27,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
28,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
29,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
30,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
31,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
32,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
33,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
34,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
35,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538
36,Fonte: IBGE - Censo Demográfico,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
dados = tabela.iloc[3:36].copy()
dados

,0,1,2,3,4,5,6,7,8,9
3,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
4,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
5,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
6,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
7,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
8,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
9,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
10,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
11,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
12,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
13,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
14,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
15,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
16,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
17,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
18,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
19,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
20,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
21,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
22,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
23,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
24,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
25,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
26,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
27,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
28,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
29,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
30,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
31,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
32,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
33,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
34,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
35,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538

In [12]:
dados.columns = [
    "regiao",
    "superior_total",
    "superior_homens",
    "superior_mulheres",
    "ctem_total",
    "ctem_homens",
    "ctem_mulheres",
    "educ_serv_saude_total",
    "educ_serv_saude_homens",
    "educ_serv_saude_mulheres",
]

In [13]:
dados = dados.reset_index(drop=True)

# Transformação das colunas numéricas para números.
for col in dados.columns[1:]:
    dados[col] = pd.to_numeric(dados[col], errors="coerce")

dados

,regiao,superior_total,superior_homens,superior_mulheres,ctem_total,ctem_homens,ctem_mulheres,educ_serv_saude_total,educ_serv_saude_homens,educ_serv_saude_mulheres
0,Brasil,25854291,10478534,15375757,4149041,2750422,1398619,8079707,1677985,6401723
1,Norte,1525166,590558,934609,209657,133055,76601,599785,141169,458616
2,Nordeste,4748933,1744994,3003939,621388,389993,231395,1822087,363905,1458181
3,Sudeste,12828829,5391638,7437191,2328122,1588874,739247,3652397,768288,2884108
4,Sul,4338861,1768855,2570005,662916,427372,235543,1256291,248574,1007718
5,Centro-Oeste,2412502,982489,1430013,326959,211124,115834,749148,156048,593101
6,Rondônia,164632,62766,101866,20538,11863,8675,63584,13963,49622
7,Acre,84300,33291,51009,10364,6237,4128,33379,9121,24258
8,Amazonas,342566,141059,201507,52669,34749,17919,121988,30738,91249
9,Roraima,67045,25585,41460,8016,4958,3057,23977,5880,18098
10,Pará,601096,229285,371811,86691,55481,31211,248397,58128,190270
11,Amapá,89191,35085,54106,11349,7464,3885,36754,9794,26960
12,Tocantins,176336,63485,112851,20028,12304,7724,71705,13548,58158
13,Maranhão,468681,161352,307329,55068,33820,21248,206222,40667,165555
14,Piauí,304955,108371,196584,37135,21668,15467,128416,25959,102457
15,Ceará,759303,285013,474290,99062,63935,35126,294578,64582,229996
16,Rio Grande do Norte,339913,131178,208735,46857,30398,16459,135434,28273,107161
17,Paraíba,390742,147221,243521,52223,33369,18855,150862,30025,120837
18,Pernambuco,852481,321587,530893,120260,73253,47007,281695,57333,224362
19,Alagoas,267996,98462,169534,33596,21398,12198,106971,20060,86911
20,Sergipe,218255,80608,137646,29020,17596,11422,83176,16801,66376
21,Bahia,1146608,411202,735406,148167,94556,53612,434735,80208,354528
22,Minas Gerais,2615434,1031532,1583902,452258,291778,160479,832482,157960,674521
23,Espírito Santo,491101,193756,297344,75667,49648,26018,161332,29788,131544
24,Rio de Janeiro,2243707,942645,1301062,406529,265723,140805,612263,145864,466399
25,São Paulo,7478587,3223705,4254883,1393668,981724,411944,2046321,434677,1611645
26,Paraná,1687930,695425,992505,255635,166579,89056,501471,98191,403280
27,Santa Catarina,1162515,489557,672958,185742,126554,59188,333537,67571,265964
28,Rio Grande do Sul,1488416,583873,904542,221541,134240,87300,421284,82812,338472
29,Mato Grosso do Sul,366249,145341,220908,46340,28241,18100,128352,26911,101443
30,Mato Grosso,450264,173267,276997,56776,33307,23468,141121,27052,114069
31,Goiás,879270,350828,528443,116867,74711,42156,288616,56564,232052
32,Distrito Federal,716719,313054,403665,106976,74866,32109,191061,45521,145538

In [ ]:
# Homens e mulheres por região com curso superior

tabela_superior = dados[
    ["regiao", "superior_homens", "superior_mulheres"]
].copy()

tabela_superior.columns = ["regiao", "homens", "mulheres"]

tabela_superior

                 regiao    homens  mulheres
0                Brasil  10478534  15375757
1                 Norte    590558    934609
2              Nordeste   1744994   3003939
3               Sudeste   5391638   7437191
4                   Sul   1768855   2570005
5          Centro-Oeste    982489   1430013
6              Rondônia     62766    101866
7                  Acre     33291     51009
8              Amazonas    141059    201507
9               Roraima     25585     41460
10                 Pará    229285    371811
11                Amapá     35085     54106
12            Tocantins     63485    112851
13             Maranhão    161352    307329
14                Piauí    108371    196584
15                Ceará    285013    474290
16  Rio Grande do Norte    131178    208735
17              Paraíba    147221    243521
18           Pernambuco    321587    530893
19              Alagoas     98462    169534
20              Sergipe     80608    137646
21                Bahia    411202    735406
22         Minas Gerais   1031532   1583902
23       Espírito Santo    193756    297344
24       Rio de Janeiro    942645   1301062
25            São Paulo   3223705   4254883
26               Paraná    695425    992505
27       Santa Catarina    489557    672958
28    Rio Grande do Sul    583873    904542
29   Mato Grosso do Sul    145341    220908
30          Mato Grosso    173267    276997
31                Goiás    350828    528443
32     Distrito Federal    313054    403665

In [20]:
tabela_superior.describe().round(2)

            homens     mulheres
count        33.00        33.00
mean     952593.97   1397796.09
std     2020681.05   2918446.17
min       25585.00     41460.00
25%      131178.00    201507.00
50%      285013.00    403665.00
75%      695425.00    992505.00
max    10478534.00  15375757.00

In [21]:
# Homens e mulheres por região com curso em Ciência, Tecnologia, Engenharias e Matemática

tabela_ctem = dados[
    ["regiao", "ctem_homens", "ctem_mulheres"]
].copy()

tabela_ctem.columns = ["regiao", "homens", "mulheres"]

tabela_ctem

                 regiao   homens  mulheres
0                Brasil  2750422   1398619
1                 Norte   133055     76601
2              Nordeste   389993    231395
3               Sudeste  1588874    739247
4                   Sul   427372    235543
5          Centro-Oeste   211124    115834
6              Rondônia    11863      8675
7                  Acre     6237      4128
8              Amazonas    34749     17919
9               Roraima     4958      3057
10                 Pará    55481     31211
11                Amapá     7464      3885
12            Tocantins    12304      7724
13             Maranhão    33820     21248
14                Piauí    21668     15467
15                Ceará    63935     35126
16  Rio Grande do Norte    30398     16459
17              Paraíba    33369     18855
18           Pernambuco    73253     47007
19              Alagoas    21398     12198
20              Sergipe    17596     11422
21                Bahia    94556     53612
22         Minas Gerais   291778    160479
23       Espírito Santo    49648     26018
24       Rio de Janeiro   265723    140805
25            São Paulo   981724    411944
26               Paraná   166579     89056
27       Santa Catarina   126554     59188
28    Rio Grande do Sul   134240     87300
29   Mato Grosso do Sul    28241     18100
30          Mato Grosso    33307     23468
31                Goiás    74711     42156
32     Distrito Federal    74866     32109

In [22]:
tabela_ctem.describe().round(2)

           homens    mulheres
count       33.00       33.00
mean    250038.18   127147.12
std     549079.01   270735.21
min       4958.00     3057.00
25%      28241.00    16459.00
50%      63935.00    32109.00
75%     166579.00    89056.00
max    2750422.00  1398619.00

In [23]:
# Homens e mulheres por região com curso em Educação, Serviços pessoais, Saúde e Bem-estar
tabela_educ_saude = dados[
    ["regiao", "educ_serv_saude_homens", "educ_serv_saude_mulheres"]
].copy()

tabela_educ_saude.columns = ["regiao", "homens", "mulheres"]

tabela_educ_saude

                 regiao   homens  mulheres
0                Brasil  1677985   6401723
1                 Norte   141169    458616
2              Nordeste   363905   1458181
3               Sudeste   768288   2884108
4                   Sul   248574   1007718
5          Centro-Oeste   156048    593101
6              Rondônia    13963     49622
7                  Acre     9121     24258
8              Amazonas    30738     91249
9               Roraima     5880     18098
10                 Pará    58128    190270
11                Amapá     9794     26960
12            Tocantins    13548     58158
13             Maranhão    40667    165555
14                Piauí    25959    102457
15                Ceará    64582    229996
16  Rio Grande do Norte    28273    107161
17              Paraíba    30025    120837
18           Pernambuco    57333    224362
19              Alagoas    20060     86911
20              Sergipe    16801     66376
21                Bahia    80208    354528
22         Minas Gerais   157960    674521
23       Espírito Santo    29788    131544
24       Rio de Janeiro   145864    466399
25            São Paulo   434677   1611645
26               Paraná    98191    403280
27       Santa Catarina    67571    265964
28    Rio Grande do Sul    82812    338472
29   Mato Grosso do Sul    26911    101443
30          Mato Grosso    27052    114069
31                Goiás    56564    232052
32     Distrito Federal    45521    145538

In [24]:
tabela_educ_saude.describe().round(2)

           homens    mulheres
count       33.00       33.00
mean    152544.24   581974.91
std     314437.31  1197881.76
min       5880.00    18098.00
25%      26911.00   101443.00
50%      56564.00   190270.00
75%     141169.00   458616.00
max    1677985.00  6401723.00

In [25]:
print(" Curso superior ")
display(tabela_superior.describe().round(2))

print(" Ciência, Tecnologia, Engenharias e Matemática ")
display(tabela_ctem.describe().round(2))

print(" Educação, Serviços pessoais, Saúde e Bem-estar ")
display(tabela_educ_saude.describe().round(2))

 Curso superior

            homens     mulheres
count        33.00        33.00
mean     952593.97   1397796.09
std     2020681.05   2918446.17
min       25585.00     41460.00
25%      131178.00    201507.00
50%      285013.00    403665.00
75%      695425.00    992505.00
max    10478534.00  15375757.00

 Ciência, Tecnologia, Engenharias e Matemática

           homens    mulheres
count       33.00       33.00
mean    250038.18   127147.12
std     549079.01   270735.21
min       4958.00     3057.00
25%      28241.00    16459.00
50%      63935.00    32109.00
75%     166579.00    89056.00
max    2750422.00  1398619.00

 Educação, Serviços pessoais, Saúde e Bem-estar

           homens    mulheres
count       33.00       33.00
mean    152544.24   581974.91
std     314437.31  1197881.76
min       5880.00    18098.00
25%      26911.00   101443.00
50%      56564.00   190270.00
75%     141169.00   458616.00
max    1677985.00  6401723.00